config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :user_accounts
  root to: redirect('/admin/user_accounts')
  get 'admin/transfer_balance', to: 'admin/transfer_balance#transfer_balance'
  post 'admin/transfer_balance', to: 'admin/transfer_balance#transfer'
  post 'admin/transfer_credit', to: 'admin/transfer_credit#credit'
  post 'admin/interest_calculator', to: 'admin/interest_calculator#calculate'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= UserAccount.new # guest user (not logged in)

      # if user.admin?
      #   can :manage, :all
      # # else if user.account_holder?
      # #   cannot :manage, :operations
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account_balance.rb
class AccountBalance < ActiveRecord::Base
  has_one :user_account
end

app/models/account_interest.rb
class AccountInterest < ActiveRecord::Base
  has_many :user_accounts
end

app/models/action.rb
class Action < ActiveRecord::Base
  has_many :transactions
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/document.rb
class Document < ActiveRecord::Base

  # Associations

  has_many :user_documents
  has_many :user_informations, through: :user_documents
end

app/models/role.rb
class Role < ActiveRecord::Base

  # Associations
  has_and_belongs_to_many :user_accounts, join_table: 'users_roles'

  ROLE_ADMIN = 'Administrator'
  ROLE_MANAGER = 'Manager'
  ROLE_STAFF = 'Staff'
  ROLE_ACCOUNT_HOLDER = 'AccountHolder'

  default_scope { order(:name) }
  scope :admin, -> {find_by(name: ROLE_ADMIN)}
  scope :manager, -> {find_by(name:  ROLE_MANAGER)}
  scope :account_holder, -> {find_by(name:  ROLE_ACCOUNT_HOLDER)}
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :source_user_account, class_name: 'UserAccount', foreign_key: 'source_user_account_id'
  belongs_to :destination_user_account, class_name: 'UserAccount', foreign_key: 'destination_user_account_id'
  belongs_to :action

  scope :mine, ->(current_user_account) { where("source_user_account_id= ? OR destination_user_account_id= ?", current_user_account, current_user_account )}

  # def action
  #   self.action.name
  # end

  def destination_account
    self.action.name == 'Credit' ? self.destination_user_account.user_name : self.source_user_account.user_name
  rescue
    nil
  end
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:user_name]

  after_save :expire
  after_update :expire


  def ability
    @ability ||= Ability.new(self)
  end
  delegate :can?, :cannot?, to: :ability

  #Associations

  belongs_to :user_information
  accepts_nested_attributes_for :user_information
  belongs_to :account_balance
  belongs_to :account_interest
  has_many :source_accounts, class_name: 'Transaction', foreign_key: 'source_user_account_id'
  has_many :destination_accounts, class_name: 'Transaction', foreign_key: 'destination_user_account_id'
  has_and_belongs_to_many :roles, join_table: 'users_roles'

  scope :total_accounts, -> {
    Rails.cache.fetch(:total_accounts) {
      self.all.count
    }
  }

  scope :total_money, -> {
    Rails.cache.fetch(:total_money) {
      self.all.includes(:account_balance).inject(0){ |val, account| val + (account.account_balance.try(:balance).presence || 0)}
    }
  }

  def expire
    UserAccount.expire_memcache(:total_money)
    UserAccount.expire_memcache(:total_accounts)
  end

  def self.expire_memcache(key)
    Rails.cache.delete(key)
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def balance
    add_zero_balance if self.account_balance.nil?
    self.account_balance.balance.try(:to_i).presence || 0
  end

  def add_zero_balance
    self.account_balance = AccountBalance.create(balance: 0)
    save!
  end

  def update_balance(amount, action)
    p "updating balance for #{amount}"
    final_amount = 0
    case action
      when :credit
        final_amount = self.balance + amount
      when :debit
        final_amount = self.balance - amount
    end
    self.account_balance.balance = final_amount
    self.account_balance.save!
    save!
  end

  def admin?
    roles.include?(Role.admin)
  end

  def manager?
    roles.include?(Role.manager)
  end

  def account_holder?
    roles.include?(Role.account_holder)
  end

  def find_for_database_authentication warden_conditions
    #raise warden_conditions.inspect
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["user_name = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:user_name) || conditions.has_key?(:account_number)
      where(conditions.to_hash).first
    end
  end
end

app/models/user_document.rb
class UserDocument < ActiveRecord::Base
  belongs_to :document
  belongs_to :user_information
end

app/models/user_information.rb
class UserInformation < ActiveRecord::Base
  has_many :user_accounts
  has_many :user_documents
  has_many :documents, through: :user_documents
  accepts_nested_attributes_for :user_accounts
  accepts_nested_attributes_for :user_documents

  after_save :expire
  after_update :expire

  def expire
    UserInformation.expire_memcache(:email_category)
  end

  def self.expire_memcache(key)
    Rails.cache.delete(key)
  end

  scope :email_category, -> {

    Rails.cache.fetch(:email_category) { UserInformation.emails_from_db }
  }

  def self.emails_from_db
    emails = Hash.new
    self.all.pluck(:email).each do |email|
      e = UserInformation.strip_mail(email)
      emails.key?(e) ? emails[e] = emails[e] + 1 : emails[e] = 1
    end
    emails
  end

  def self.strip_mail(str)
    length = str.length
    at = str.index('@')
    return at.nil? ? str : str[at+1, length]
  end

end

app/controllers/account_interests_controller.rb
class AccountInterestsController < InheritedResources::Base

  private

    def account_interest_params
      params.require(:account_interest).permit(:interest, :account_name)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < InheritedResources::Base

  private

    def document_params
      params.require(:document).permit(:name)
    end
end

app/controllers/roles_controller.rb
class RolesController < InheritedResources::Base

  private

    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/account_balances_helper.rb
module AccountBalancesHelper
end

app/helpers/account_interests_helper.rb
module AccountInterestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/helpers/user_documents_helper.rb
module UserDocumentsHelper
end

app/helpers/user_informations_helper.rb
module UserInformationsHelper
end

app/views/account_interests/_form.html.erb
<%= form_for(@account_interest) do |f| %>
  <% if @account_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_interest.errors.count, "error") %> prohibited this account_interest from being saved:</h2>

      <ul>
      <% @account_interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :account_name %><br>
    <%= f.text_field :account_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_interests/edit.html.erb
<h1>Editing Account Interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_interest %> |
<%= link_to 'Back', account_interests_path %>

app/views/account_interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Account Interests</h1>

<table>
  <thead>
    <tr>
      <th>Interest</th>
      <th>Account name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_interests.each do |account_interest| %>
      <tr>
        <td><%= account_interest.interest %></td>
        <td><%= account_interest.account_name %></td>
        <td><%= link_to 'Show', account_interest %></td>
        <td><%= link_to 'Edit', edit_account_interest_path(account_interest) %></td>
        <td><%= link_to 'Destroy', account_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account interest', new_account_interest_path %>

app/views/account_interests/new.html.erb
<h1>New Account Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', account_interests_path %>

app/views/account_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interest:</strong>
  <%= @account_interest.interest %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @account_interest.account_name %>
</p>

<%= link_to 'Edit', edit_account_interest_path(@account_interest) %> |
<%= link_to 'Back', account_interests_path %>